language: node_js
node_js: node

install:
    - npm install gitbook-cli -g
    - gitbook install

script:
    - gitbook build

after_script:
    - cd _book
    - git init
    - git config user.name "mzlogin"
    - git config user.email "chumpma@gmail.com"
    - git add .
    - git commit -m "Publish"
    - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

branches:
    only:
        - master

git:
    depth: 3
